apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
  namespace: iot-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
        - name: iot-simulator
          image: iot-simulator:latest
          envFrom:
            - configMapRef:
                name: iot-health-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
