apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-health

resources:
  - namespace.yaml
  - configmap.yaml
  - kafka/kafka-cluster.yaml
  - kafka/kafka-topic.yaml
  - secrets/external-secret.yaml
  - minio/minio-deployment.yaml
  - iot-simulator/deployment.yaml
  - iot-simulator/hpa.yaml
  - spark-streaming/deployment.yaml
  - spark-streaming/hpa.yaml
  - model-trainer/cronjob.yaml
