version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  iot_simulator:
    build: ./iot_simulator
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  kafka_producer:
    build: ./kafka_producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  spark_streaming:
    build: ./spark_streaming
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  anomaly_detection:
    build: ./anomaly_detection
    depends_on:
      - spark_streaming
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  sagemaker_training:
    build: ./sagemaker
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./sagemaker:/app/sagemaker
      - sagemaker_output:/opt/ml/model

volumes:
  sagemaker_output: