Description: 'CloudFormation template for long term image repo, ecs cluster'
Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: iot-ecr

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: iot-cluster

Outputs:
  PublicSubnetId:
    Description: "ID of the Public Subnet"
    Value: Fn::ImportValue: 
      'Fn::Sub': '${EnvironmentName}-PUB-NETS'
    Export:
      Name: !Sub "${EnvironmentName}-PublicSubnetId"

  EC2SecurityGroupId:
    Description: "ID of the EC2 Security Group"
    Value: !ImportValue "${EnvironmentName}-EC2SecurityGroup"
    Export:
      Name: !Sub "${EnvironmentName}-EC2SecurityGroupId"