Description: 'CloudFormation template for long term image repo, ecs cluster'
Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: iot-ecr

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: iot-cluster